# Generated by Django 6.0.7 on 2026-08-04 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('supports_oauth', models.BooleanField(default=False)),
                ('supports_publish', models.BooleanField(default=False)),
                ('supports_analytics', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=120)),
                ('profile_url', models.URLField()),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('connection_status', models.CharField(default='url_only', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='social_channels.socialplatform')),
            ],
            options={
                'unique_together': {('user', 'platform', 'profile_url')},
            },
        ),
    ]
