# Generated by Django 6.0.7 on 2026-08-04 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PressProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_name', models.CharField(max_length=150)),
                ('homepage_url', models.URLField()),
                ('rss_url', models.URLField()),
                ('rss_verified', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, upload_to='press_logos/')),
                ('auto_collect', models.BooleanField(default=True)),
                ('last_collected_at', models.DateTimeField(blank=True, null=True)),
                ('collection_status', models.CharField(default='pending', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='press_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
